### ISSUE TITLE
NullPointerException being thrown in BindingListViewAdapter.java

### ISSUE THREAD

**Issue by shankera** [evant/binding-collection-adapter#5]
I have only been able to replicate this bug on an Android device version 4.1.2. The NullPointer happens on "itemView.layoutRes" in getItemViewType(). While debugging through the constructor, the ItemView parameter WAS null. The relevant part of the stacktrace has been posted below.

    java.lang.NullPointerException
            at me.tatarka.bindingcollectionadapter.BindingListViewAdapter.getItemViewType(BindingListViewAdapter.java:192)
            at me.tatarka.bindingcollectionadapter.BindingListViewAdapter.getView(BindingListViewAdapter.java:144)
            at android.widget.AbsListView.obtainView(AbsListView.java:2340)
            at android.widget.ListView.onMeasure(ListView.java:1271)

If you have any insight as to why this is occurring, or if you require more information, please let me know.

Update: I have been able to replicate this on v4.0.4 and v4.2 devices as well.

**Comment by shankera** [comment]
We were able to circumvent this problem. 

Originally, we had one xml file that included another, which had a list view in it. This list view had data set after a service call finished, and then the application crashed. We removed the include, combined both xml files, and merged the associated viewmodels. This fixed the issue.

**Comment by evant** [comment]
If you get a chance, can you create a sample project that shows an example of layouts that causes the issue?

**Comment by shankera** [comment]
Sure, ill try and have that for you this evening

**Comment by shankera** [comment]
I've commited an example project here. https://github.com/shankera/ExampleDatabindingProject

I had to reduce the content considerably, but the important parts are all still there. If something is unclear, please let me know so I can clarify

**Comment by evant** [comment]
Your example didn't seem complete. However, going from the stacktrace I think I've fixed this issue in `0.11` when testing Spinner support. Can you test with the new version when you get a chance?

**Comment by shankera** [comment]
Retested it with the new version, application still crashes with the same stacktrace

**Comment by evant** [comment]
Can you update your sample project? Everything doesn't seem hooked up. I tried doing it myself, but then I couldn't reproduce the crash.

**Comment by shankera** [comment]
Yeah, I can update it this week.

**Comment by evant** [comment]
Closing for lack of information. Feel free to reopen if you can update the sample project to reproduce the issue.
